### PR TITLE
Add compile guide

### PR DESCRIPTION
**Pull request by XP1**
Add compile guide

### CODE REVIEW

**Comment by winauth** [comment]
I don't have the Win 8.1 SDK installed. WinAuth is old enough that it doesn't make use of it. What makes you think it's needed?

**Comment by XP1** [comment]
Don't know why I needed it. Maybe a default setting in VS2017? Instead of figuring out why, I just installed Windows 8.1 SDK, and the error went away afterwards.

This was the error I got when I first tried to build:

> Severity Code Description Project File Line Suppression State Error
> MSB8036 The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". WinAuth.YubiKey.x86 C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Platforms\Win32\PlatformToolsets\v141\Toolset.targets 34

**Comment by winauth** [comment]
I'm going to try to build it on a clean VM and see it it works. Maybe I have some old remnants of an SDK on my machine.

**Comment by winauth** [comment]
Well, it does seem you need 8.1 SDK for compatibility, although when I installed VS 2017 it automatically installed the Windows 10 SDK which can be then be selected as the target platform instead.

Perhaps change the instructions to something like "You will need to either install the Windows 8.1 SDK or change the TargetPlatform for the YubiKey projects to your existing SDK".

**Pull request merged**
